# Jekyll
safe: true
lsi: false
pygments: true
markdown: rdiscount
permalink: /:title.html

# Conference info
conf:
  name: "Hack &amp; Design Conference'13"
  description: "O Hack & Design Conference, aka HDC'13, une as comunidades de hacking e codificação com a comunidade de design."
  date: "05/10/2013"
  price: "R$130"
  address: "UNIRIO - Prédio CCET - Av. Pasteur, nº 458, sala 203 - Urca"
  venue: ""
  city: "Rio de Janeiro"

# Site info
site:
  url: "http://hackdesignconf.com.br/"
  favicon: "/img/favicon.png"
  googleanalytics: "UA-33656081-1"
  images:
    cover: "http://hackdesignconf.com.br/img/facebook.png"
    facebook: "http://hackdesignconf.com.br/img/facebook.png"

# Active sections on the website
sections:
  about: true
  conditions: true
  location: true
  speakers: true
  hotels: true
  schedule: true
  sponsors: false
  partners: true
  contact: false



schedule:
#  -
#    name: "Credenciamento"
#    time: "9h00"
  -
    name: "Emilio Cini Simoni"
    photo: "emilio.png"
    bio: "Emilio é desenvolvedor de software há 16 anos, especialista em segurança da informação. Trabalha como diretor de pesquisa e inovação na GAS Tecnologia há 10 anos especificamente na área de combate a fraude contra internet banking."
    company: "GAS Tecnologia"
    twitter: ""
    linkedin: "http://www.linkedin.com/pub/emilio-simoni/10/9a6/242"
    presentation:
      title: "Ecossistema Underground"
      description: "Como surgem os bankers, como são formadas as quadrilhas, sistemas de fraude, mercado negro, meios de comunicação e analise macro de fraudes."
  -
    name: "Barbara Wolff Dick"
    photo: "barbara.png"
    bio: "Barbar é designer digital, estrategista de inovação social e entusiasta de novas mídias. Ajuda as pessoas a alcançar seus objetivos através do bom design e experiências simples."
    company: "Engage e Pipa"
    twitter: "barbarawdick"
    presentation:
      title: "O Design que precisamos: livre, aberto e colaborativo"
      description: "O Open Design está silenciosamente mudando a industria criativa, abrindo caminhos para uma economia mais colaborativa, tanto para designers e desenvolvedores, como para usuários e consumidores. Aplicando os princípios do software livre, as iniciativas também se baseiam na ideia de que a criatividade e, principalmente a sociedade, se beneficiam do livre acesso a informação. Então, com esse cenário se formando, como podemos aplicar esses processos disruptivos em busca de resultados extraordinários, abertos e livres, e começar a mudar a narrativa do Design? "
#  -
#    name: "Almoço"
#    time: "12h00"
  -
    name: "Pedro Franceschi"
    photo: "franceschi.png"
    bio: "Pedro é desenvolvedor de software desde os 14 anos de idade e já palestrou em diversos eventos, dentre eles o TEDxSudeste. Foi o responsável por ensinar o Siri, aplicativo de voz do iPhone a falar Português."
    company: "M4U"
    twitter: "pedroh96"
    presentation:
      title: ""
      description: "Palestra não definida."
  -
    name: "Victor Montalvão"
    photo: "victor.png"
    bio: "Victor é Designer com foco em experiência do usuário e especialista em usabilidade pela PUC-Rio. Atuando no mercado desde 2003, participou de diversos projetos digitais para empresas e instituições no Brasil, Canadá e Austrália. Atualmente integra o time de UX na área de Novas Mídias da Globosat, atuando em projetos para mobile, web, smart tvs e consoles de games."
    company: "Globosat"
    twitter: ""
    presentation:
      title: ""
      description: "Palestra não definida."

  -
    name: "Klaus Wuestefeld"
    photo: "klaus.png"
    bio: "Klaus é palestrante em eventos como o Fórum Internacional de Software Livre, a OOPSLA nos EUA, ICOODB em Berlin, DevInSampa, QCon e Agile Brasil. Jogador de Go e chefe escoteiro, ele é pioneiro de Extreme Programming no país e autor do Prevayler, um dos projetos de software livre brasileiros mais conhecidos no exterior. É fundador da Objective Solutions e autor do manifesto da computação soberana."
    company: "Objective Solutions e Sneer"
    twitter: ""
    presentation:
      title: "Bem-Vindo à Computação Soberana, à Queda do Google e ao Fim do Facebook"
      description: "Usuários de Software Livre ou não, todos não passavam de súditos. Subjugados por um punhado de autoridades da internet, conformavam-se às leis arbitrárias, ditadas por elas. Aí, as pessoas cansaram dessa palhaçada. Decidiram que seriam livres para compartilhar informação e recursos de hardware com seus amigos, da forma como bem entendessem. Essa liberdade ficou conhecida como computação soberana."

# List of Sponsors
sponsors:
  -
    name: "Eventick"
    logo: "http://f.cl.ly/items/1U3p0Z0e2w0I1i3z1X22/Image%202012.09.25%203:00:58%20PM.png"
    url: "http://eventick.com.br"

# List of Partners
partners:
  -
    name: "BrazilJS"
    logo: "http://f.cl.ly/items/2N3i2W0X2f3c2g2Z2N0f/Untitled-1.png"
    url: "http://braziljs.org"
