# Jekyll
server: true
auto: true
markdown: rdiscount
pygments: true
permalink: /:title.html

# Conference info
conf:
  name: "Hack &amp; Design Conference'13"
  description: "O Hack & Design Conference, aka HDC'13, une as comunidades de hacking e codificação com a comunidade de design."
  date: "05/10/2013"
  price: "R$130"
  address: "UNIRIO - Prédio CCET - Av. Pasteur, nº 458, sala 203 - Urca"
  venue: ""
  city: "Rio de Janeiro"

# Site info
site:
  url: "http://hackdesignconf.com.br/"
  favicon: "/img/favicon.png"
  googleanalytics: "UA-33656081-1"
  images:
    cover: "http://hackdesignconf.com.br/img/facebook.png"
    facebook: "http://hackdesignconf.com.br/img/facebook.png"

# Active sections on the website
sections:
  about: true
  conditions: true
  location: true
  speakers: true
  hotels: true
  schedule: true
  sponsors: false
  partners: true
  contact: false



schedule:
  -
    name: "Check-in / Breakfast"
    time: "9h00"
  -
    name: "Emilio Cini Simoni"
    photo: "./img/photos.png"
    bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    company: "Linux Foundation"
    twitter: ""
    presentation:
      title: "Ecossistema Underground"
      description: "Como surgem os bankers, como são formadas as quadrilhas, sistemas de fraude, mercado negro, meios de comunicação e analise macro de fraudes."
      time: "10h00"
  -
    name: "Barbara Wolf Dick"
    photo: "./img/photos2.png"
    bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    company: "Engage"
    twitter: "barbarawdick"
    presentation:
      title: "O Design que precisamos: livre, aberto e colaborativo."
      description: "O Open Design está silenciosamente mudando a industria criativa, abrindo caminhos para uma economia mais colaborativa, tanto para designers e desenvolvedores, como para usuários e consumidores. Aplicando os princípios do software livre, as iniciativas também se baseiam na ideia de que a criatividade e, principalmente a sociedade, se beneficiam do livre acesso a informação.
      Então, com esse cenário se formando, como podemos aplicar esses processos disruptivos em busca de resultados extraordinários, abertos e livres, e começar a mudar a narrativa do Design? "
      time: "11h00"
  -
    name: "Lunch"
    time: "12h00"
  
  

# List of Sponsors
sponsors:
  -
    name: "Eventick"
    logo: "http://f.cl.ly/items/1U3p0Z0e2w0I1i3z1X22/Image%202012.09.25%203:00:58%20PM.png"
    url: "http://eventick.com.br"

# List of Partners
partners:
  -
    name: "BrazilJS"
    logo: "http://f.cl.ly/items/2N3i2W0X2f3c2g2Z2N0f/Untitled-1.png"
    url: "http://braziljs.org"